USE SCHEMA DEMO;
INSERT INTO  HELLO_WORLD VALUES ('VAMSHI','REDDY','31');
INSERT INTO  HELLO_WORLD VALUES ('VINDO','REDDY','33');
INSERT INTO  HELLO_WORLD VALUES ('HANVI','REDDY','01');
INSERT INTO  HELLO_WORLD VALUES ('ARCHANA','REDDY','32');